import { DemoCenter } from "./dataTypes";

export const defaultPaginatedData = {
  data: [],
  meta: {
    page: 1,
    limit: 10,
    total: 0,
  },
};

export const demoCentersData: DemoCenter[] = [
  {
    id: "1",
    buildingType: "business",
    name: "Hardcore Fitness Huntington Beach",
    address: "17711 Crabb Ln",
    contact: "714-912-1923",
    cityZip: "Huntington Beach, CA 92647",
    bio: "Premier fitness facility offering state-of-the-art equipment and personalized training programs. Our Huntington Beach location features the latest in fitness technology and a supportive community atmosphere.",
    image: "/assets/demo-center-1.jpg",
    availability: "Contact for availability",
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekends: ["Saturday", "Sunday"],
    weekdayOpen: "5:00 AM",
    weekdayClose: "8:15 PM",
    weekendOpen: "6:00 AM",
    weekendClose: "12:00 PM",
    isPublic: true,
    blocked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    buildingType: "business",
    name: "Hardcore Fitness Long Beach",
    address: "301 Pine Ave",
    contact: "719-552-2767",
    cityZip: "Long Beach, CA 90802",
    bio: "Our Long Beach facility combines modern fitness equipment with expert guidance. Featuring specialized training areas and group fitness classes for all fitness levels.",
    image: "/assets/demo-center-1.jpg",
    availability: "Contact for availability",
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekends: ["Saturday", "Sunday"],
    weekdayOpen: "5:00 AM",
    weekdayClose: "9:00 PM",
    weekendOpen: "5:00 AM",
    weekendClose: "9:00 PM",
    isPublic: true,
    blocked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    buildingType: "isolator",
    name: "Elite Fitness Center Irvine",
    address: "456 Technology Dr",
    contact: "949-555-1234",
    cityZip: "Irvine, CA 92618",
    bio: "Specialized isolation training facility focusing on targeted muscle development. Our Irvine location offers cutting-edge isolation equipment for precise workout routines.",
    image: "/assets/demo-center-1.jpg",
    availability: "Appointment required",
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekends: ["Saturday", "Sunday"],
    weekdayOpen: "6:00 AM",
    weekdayClose: "10:00 PM",
    weekendOpen: "7:00 AM",
    weekendClose: "8:00 PM",
    isPublic: true,
    blocked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    buildingType: "business",
    name: "Powerhouse Gym Anaheim",
    address: "789 Main St",
    contact: "714-555-9876",
    cityZip: "Anaheim, CA 92801",
    bio: "Full-service gym with comprehensive equipment and training programs. Our Anaheim location serves the local community with quality fitness solutions.",
    image: "/assets/demo-center-1.jpg",
    availability: "Walk-ins welcome",
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekends: ["Saturday", "Sunday"],
    weekdayOpen: "4:00 AM",
    weekdayClose: "11:00 PM",
    weekendOpen: "5:00 AM",
    weekendClose: "10:00 PM",
    isPublic: true,
    blocked: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
